# yaml 파일은 탭을 사용하면 안됨
# init: true // 안정적인 자식 프로세스 관리
services:
  nginx:
    build: ./services/proxy
    image: proxy:hyeongsh
    container_name: proxy
    environment: 
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./services/frontend/src:/usr/share/nginx/html
    depends_on:
      frontend:
        condition: service_healthy
  
  frontend:
    build: ./services/frontend
    image: frontend:hyeongsh
    container_name: frontend
    enviorment:
    volumes:
      - ./services/frontend/src:/app
      - /app/node_modules # 호스트의 npm 모듈과 겹치지 않도록 익명 볼륨으로 따로 관리
    healthcheck:
      test: wget -qO- http://frontend:5173/
      interval: 10s
      timeout: 10s
      retries: 5
    tty: true # 서버가 죽지 않고 계속 살아 있을 수 있음 -> frontend 서버는 코드 제공용이므로 제공한 후로도 남아 있어야 함.
  